# config
logo: //blog.ghost.org/content/images/2013/Nov/bloglogo_1-1.png
favicon: //blog.ghost.org/content/images/2013/Nov/bloglogo_1-1.png
bio: 'An undergrad student majoring in computer science.'

# Content
excerpt_link: Read More

# Miscellaneous
rss:
